"""empty message

Revision ID: 1f7f45938ad9
Revises: d9cb1566ac7c
Create Date: 2023-01-27 10:12:04.011615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7f45938ad9'
down_revision = 'd9cb1566ac7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
