"""empty message

Revision ID: 8abb1302e99e
Revises: 1f7f45938ad9
Create Date: 2023-01-27 10:52:49.335981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abb1302e99e'
down_revision = '1f7f45938ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('family_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
