"""empty message

Revision ID: d9cb1566ac7c
Revises: aa1398f20441
Create Date: 2023-01-27 09:26:41.749537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cb1566ac7c'
down_revision = 'aa1398f20441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
